# Generated by Django 5.1.3 on 2024-12-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_cloth_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cloth',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
